#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""adventure_gui.py —— 冒险游戏的图形界面外壳（学生不需要修改这个文件）
adventure_gui.py —— Graphical front-end for the Adventure Game (students do NOT edit this file)

怎么运行 / How to run:
    python3 adventure_gui.py

它做了什么 / What it does:
    * 读取 data.py 与 classes.py，把当前地点、出口、物品、角色、背包画成按钮和面板；
      It reads data.py / classes.py and draws the current place, exits, things,
      characters and backpack as buttons and panels.
    * 你点击按钮时，它调用的是**你自己写的** Player.go_to / take / talk_to / unlock，
      并把 print 出来的文字显示在日志窗口里；
      Clicking a button calls *your* Player.go_to / take / talk_to / unlock and shows
      whatever they print inside the log window.
    * 所以：只要改 classes.py 和 data.py，界面会自动跟着变，不需要动这个文件。
      So you only edit classes.py and data.py; this file never needs changes.

其它 / Notes:
    * 顶部“重新加载代码”可以在改完 classes.py / data.py 之后热重载，不用重启程序。
      The "Reload code" button re-imports classes.py / data.py without restarting.
    * 界面用 Python 自带的 tkinter（Windows/macOS/Linux 的官方 Python 都自带）。
      The interface uses tkinter, which ships with the official Python installers.
    * 如果你更喜欢纯文字版，运行 `python3 adventure.py` 即可，两者玩法完全一样。
      The text version (`python3 adventure.py`) still works and plays identically.
"""

import builtins
import importlib
import io
import os
import sys
import traceback

try:
    import tkinter as tk
    from tkinter import font as tkfont
    from tkinter import messagebox
    from tkinter import scrolledtext
    from tkinter import ttk
except ImportError:  # pragma: no cover - 只在缺少 tkinter 的环境下触发
    sys.stderr.write(
        '无法导入 tkinter，图形界面不能启动。\n'
        'Tkinter is not available, so the graphical interface cannot start.\n\n'
        '  1. 先确认你的 Python 里带 tkinter：python3 -c "import tkinter"\n'
        '     Check your Python has tkinter: python3 -c "import tkinter"\n'
        '  2. Windows 重新安装 Python 时请勾选 "tcl/tk and IDLE"。\n'
        '     On Windows, re-install Python with the "tcl/tk and IDLE" option.\n'
        '  3. macOS 建议用 python.org 的官方安装包（Homebrew 的 python-tk 也可以）。\n'
        '     On macOS prefer the python.org installer (or `brew install python-tk`).\n'
        '  4. 也可以继续使用文字版：python3 adventure.py\n'
        '     You can always fall back to the text version: python3 adventure.py\n')
    raise SystemExit(1)


# =============================================================================
# 一些固定配置 / Fixed configuration
# =============================================================================

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
WINDOW_TITLE = '校园冒险游戏 Adventure Game'

# 胜利条件（与 adventure.py 中的 check_win_state 一致）/ Same win condition as adventure.py
WIN_ITEM_NAMES = ('Smoothie', 'Lemon')
WIN_PLACE_NAMES = ('大礼堂', 'HP Auditorium', 'HP', 'Auditorium')

# 界面语言 / UI language:  'both' = 中英双语, 'zh' = 中文, 'en' = English
LANG = 'both'

LANGUAGE_CHOICES = (
    ('both', '双语 Both'),
    ('zh', '中文'),
    ('en', 'English'),
)

# 每个待完成方法的“一句话提示” / One-line reminder for each stub.
METHOD_HINTS = (
    ('go_to',
     'Player.go_to：目的地没上锁就移动过去，然后打印 `You are at <地点名>, <描述>.`。',
     'Player.go_to: move when the destination is not locked, then print '
     '`You are at <name>, <description>.`'),
    ('talk_to',
     'Player.talk_to：名字 -> Character 对象 -> 取出台词并打印。',
     'Player.talk_to: name -> Character object -> print its message.'),
    ('take',
     'Player.take：把物品从原地拿走，放进 self.backpack。',
     'Player.take: move the thing out of the place into self.backpack.'),
    ('unlock',
     'Player.unlock：背包里有钥匙才能解锁相邻的上锁地点。',
     'Player.unlock: you need a key in your backpack to unlock a locked place.'),
)


def T(zh, en):
    """按照当前界面语言返回文本 / Return text in the currently selected language."""
    if LANG == 'zh':
        return zh
    if LANG == 'en':
        return en
    if '\n' in zh or '\n' in en:
        return zh + '\n' + en
    return zh + ' / ' + en


def _read_lines(path):
    """读取源文件的所有行（容错编码）/ Read a source file, tolerating bad encodings."""
    try:
        with open(path, 'r', encoding='utf-8', errors='replace') as handle:
            return handle.read().splitlines()
    except OSError:
        return []


def _localize(name, data_module):
    """把英文别名换成 data.py 中的标准名字（与 adventure.py 的规则保持一致）。"""
    aliases = getattr(data_module, 'ALIASES', None) or {}
    if name in aliases:
        return aliases[name]
    return aliases.get(name.lower(), name)


def _simple_parse(line, data_module=None):
    """adventure.py 不可用时的备用解析器 / Fallback parser used if adventure.py fails."""
    tokens = line.split()
    if not tokens:
        raise SyntaxError(T('没有输入命令', 'No command given'))
    command = tokens.pop(0)
    if command in ('talk', 'go'):
        if not tokens or tokens[0] != 'to':
            raise SyntaxError(T('你是想说 "{} to [名字]" 吗？'.format(command),
                                'Did you mean "{} to [name]"?'.format(command)))
        operator, operand = command + '_to', ' '.join(tokens[1:])
    elif command == 'check':
        if not tokens or tokens[0] != 'backpack':
            raise SyntaxError(T('你是想说 "check backpack" 吗？',
                                'Did you mean "check backpack"?'))
        operator, operand = 'check_backpack', ''
    elif command == 'unlock':
        operator, operand = 'unlock', ' '.join(tokens)
    else:
        operator, operand = command, ' '.join(tokens)
    if operator in ('go_to', 'talk_to', 'take', 'unlock'):
        operand = _localize(operand, data_module)
    return (operator, operand)


# =============================================================================
# GameSession：把学生写的游戏逻辑包起来，给界面调用
# GameSession: wraps the student's game logic so the interface can call it
# =============================================================================

class GameSession(object):
    """负责载入代码、调用玩家方法、捕获输出、判断状态的工作。"""

    def __init__(self):
        self.classes = None
        self.data = None
        self.me = None
        self.adventure = None
        self.load_error = None
        self.places = []
        self.load(do_reload=False)

    # ---------------------------------------------------------------- 载入
    def load(self, do_reload=False):
        """导入（或重新导入）classes.py 与 data.py，成功返回 True。"""
        if PROJECT_DIR not in sys.path:
            sys.path.insert(0, PROJECT_DIR)
        self.load_error = None
        self.classes = self.data = self.me = None
        self.places = []
        try:
            classes_module = importlib.import_module('classes')
            if do_reload:
                classes_module = importlib.reload(classes_module)
            data_module = importlib.import_module('data')
            if do_reload:
                data_module = importlib.reload(data_module)
            if do_reload and 'adventure' in sys.modules:
                importlib.reload(sys.modules['adventure'])
        except Exception:
            self.load_error = traceback.format_exc()
            return False
        self.classes = classes_module
        self.data = data_module
        self.me = getattr(data_module, 'me', None)
        self.adventure = sys.modules.get('adventure')
        self.places = [value for value in vars(data_module).values()
                       if isinstance(value, classes_module.Place)]
        return True

    # ---------------------------------------------------------------- 查询
    def has_player(self):
        """data.py 里是否已经创建了 Player 对象。"""
        if self.classes is None or self.me is None:
            return False
        try:
            return isinstance(self.me, self.classes.Player)
        except AttributeError:
            return False

    def place(self):
        """玩家当前所在的 Place（没有就返回 None）。"""
        return getattr(self.me, 'place', None) if self.me is not None else None

    def view(self):
        """把当前状态整理成界面直接可以画出来的字典。"""
        place = self.place()
        if place is None:
            return None
        info = {
            'name': getattr(place, 'name', '?'),
            'description': getattr(place, 'description', ''),
            'locked': bool(getattr(place, 'locked', False)),
            'exits': [],
            'things': [],
            'characters': [],
            'backpack': [],
        }
        for exit_name, exit_value in getattr(place, 'exits', {}).items():
            description = ''
            if isinstance(exit_value, (tuple, list)) and exit_value:
                target = exit_value[0]
                if len(exit_value) > 1 and exit_value[1]:
                    description = exit_value[1]
            else:
                target = exit_value
            info['exits'].append({
                'name': getattr(target, 'name', exit_name) or exit_name,
                'description': description,
                'locked': bool(getattr(target, 'locked', False)),
            })
        for thing in getattr(place, 'things', {}).values():
            info['things'].append({
                'name': getattr(thing, 'name', '?'),
                'description': getattr(thing, 'description', ''),
            })
        for name, character in getattr(place, 'characters', {}).items():
            info['characters'].append({'name': getattr(character, 'name', name)})
        for item in (getattr(self.me, 'backpack', None) or []):
            info['backpack'].append({
                'name': getattr(item, 'name', str(item)),
                'description': getattr(item, 'description', ''),
            })
        return info

    def signature(self):
        """游戏状态的“指纹”，用来判断一次操作有没有真的改变状态。"""
        place = self.place()
        backpack = tuple(sorted(getattr(item, 'name', str(item))
                                for item in (getattr(self.me, 'backpack', None) or [])))
        locks = tuple(sorted((getattr(place_object, 'name', str(place_object)),
                              bool(getattr(place_object, 'locked', False)))
                             for place_object in self.places))
        return (id(place), backpack, locks)

    def is_win(self):
        """是否达成了胜利条件（在大礼堂 + 背包里有 Smoothie 和 Lemon）。"""
        try:
            place = self.place()
            if place is None:
                return False
            if place is not getattr(self.data, 'hp', None) \
                    and getattr(place, 'name', '') not in WIN_PLACE_NAMES:
                return False
            names = {getattr(item, 'name', str(item))
                     for item in (getattr(self.me, 'backpack', None) or [])}
            return set(WIN_ITEM_NAMES).issubset(names)
        except Exception:
            return False

    # ---------------------------------------------------------------- 调用
    def _capture(self, function, *args):
        """执行学生代码，并把它 print 出来的文字收集起来。"""
        buffer = io.StringIO()
        real_stdout, real_input = sys.stdout, builtins.input

        def blocked_input(prompt=''):
            raise EOFError(T(
                '图形界面里不能使用 input()，请使用界面按钮或下方的命令输入框。',
                'input() is not available in the GUI - use the buttons or the command box.'))

        sys.stdout = buffer
        builtins.input = blocked_input
        error = None
        try:
            function(*args)
        except Exception:
            error = traceback.format_exc()
        finally:
            sys.stdout = real_stdout
            builtins.input = real_input
        return buffer.getvalue(), error

    def call(self, method_name, *args):
        """调用学生自己实现的 Player 方法，返回 (输出文本, 错误信息或 None)。"""
        if self.me is None:
            return (T('data.py 的最后一行还没有创建 Player 对象，所以还没法玩。',
                      'There is no Player object at the bottom of data.py yet, so the game '
                      'cannot start.'), None)
        method = getattr(self.me, method_name, None)
        if method is None:
            return (T('Player 类里没有 {} 方法。'.format(method_name),
                      'The Player class has no {} method.'.format(method_name)), None)
        return self._capture(method, *args)

    def parse(self, line):
        """解析一行命令；优先用 adventure.py 的解析器，保证与文字版完全一致。"""
        if self.adventure is None and self.data is not None:
            try:
                importlib.import_module('adventure')
            except Exception:
                self.adventure = None
            else:
                self.adventure = sys.modules.get('adventure')
        parser = getattr(self.adventure, 'adv_parse', None)
        if parser is not None:
            return parser(line)
        return _simple_parse(line, self.data)

    def command_formats(self):
        """命令列表（来自 adventure.py，取不到就用备用列表）。"""
        formats = getattr(self.adventure, 'COMMAND_FORMATS', None)
        if formats:
            return list(formats.values())
        return [
            'look                     # 看看周围',
            'go to [place]             # 去往某个地点',
            'take [thing]              # 拿走某个物品',
            'talk to [character]       # 和某个角色交谈',
            'check backpack            # 查看背包',
            'help                      # 显示命令列表',
            'unlock [place]            # 用钥匙解锁某个地点',
        ]

    # ---------------------------------------------------------------- 提示
    def remaining_stubs(self):
        """找出 classes.py / data.py 里还没删掉的 "*** YOUR CODE HERE ***"。"""
        stubs = []
        for module in (self.classes, self.data):
            path = getattr(module, '__file__', None)
            if not path:
                continue
            for number, line in enumerate(_read_lines(path), 1):
                if '*** YOUR CODE HERE ***' in line or 'Implement Key here' in line:
                    stubs.append((path, number, line.strip()))
        return stubs

    def stub_line(self, method_name):
        """返回 classes.py 里某个方法内 YOUR CODE HERE 的行号（找不到就返回 None）。"""
        if self.classes is None:
            return None
        path = getattr(self.classes, '__file__', None)
        if not path:
            return None
        lines = _read_lines(path)
        start = None
        for index, line in enumerate(lines):
            if line.lstrip().startswith('def {}('.format(method_name)):
                start = index
                break
        if start is None:
            return None
        indent = len(lines[start]) - len(lines[start].lstrip())
        for index in range(start + 1, len(lines)):
            stripped = lines[index].strip()
            current_indent = len(lines[index]) - len(lines[index].lstrip())
            if stripped.startswith('def ') and current_indent <= indent:
                break
            if '*** YOUR CODE HERE ***' in stripped:
                return index + 1
        return None

    def location_of(self, method_name):
        """给出方法的位置描述，例如 'classes.py:31'。"""
        line = self.stub_line(method_name)
        if line is None:
            return 'classes.py'
        return 'classes.py:{}'.format(line)

    def no_change_hint(self, method_name):
        """操作之后状态没有变化时，给出的双语提示。"""
        where = self.location_of(method_name)
        if method_name == 'go_to':
            return T(
                '咦，玩家好像没有移动：Player.go_to 可能还没写完（{}）。另外，如果目的地旁边有 🔒，'
                '说明它上锁了，需要先找到钥匙再用 unlock。'.format(where),
                'Hmm, the player did not move: Player.go_to looks unfinished ({}). '
                'Also, if the destination shows a 🔒 it is locked - find the key and unlock it '
                'first.'.format(where))
        if method_name == 'take':
            return T(
                '背包没有变化：Player.take 可能还没写完（{}），或者这件物品根本不在你所在的地点。'.format(where),
                'The backpack did not change: Player.take looks unfinished ({}), or the thing is '
                'simply not where you are.'.format(where))
        if method_name == 'unlock':
            return T(
                '这门还是锁着：Player.unlock 可能还没写完（{}），或者你的背包里还没有钥匙。'.format(where),
                'The place is still locked: Player.unlock looks unfinished ({}), or there is no key '
                'in your backpack yet.'.format(where))
        if method_name == 'talk_to':
            return T(
                '聊天好像没有任何输出：Player.talk_to 可能还没写完（{}）。'.format(where),
                'Talking produced no output: Player.talk_to looks unfinished ({}).'.format(where))
        return T('这次操作好像没有改变任何状态（{}）。'.format(where),
                 'That action did not change anything ({}).'.format(where))

    def error_hint(self, method_name):
        """学生代码抛异常时的双语说明。"""
        if method_name == 'unlock':
            return T(
                '提示：unlock 里会用到 Key 类，如果你还没有实现 Key，就会看到 NameError。'
                '请先在 classes.py 里写完 Key（它是 Thing 的子类）。',
                'Hint: unlock uses the Key class. Until you implement Key you will see a NameError - '
                'write the Key class in classes.py first (it is a subclass of Thing).')
        return T(
            '上面是 Python 报的错。看看 {} 里的代码，再对照它的 docstring（doctest）检查一下。'.format(
                self.location_of(method_name)),
            'That is the Python error. Re-read {} and compare with its docstring (the doctests).'.format(
                self.location_of(method_name)))

    def hint_lines(self):
        """“提示”按钮显示的内容（中英双语）。"""
        lines = [
            T('目标：带上一杯奶昔（Smoothie）和一个柠檬（Lemon），去大礼堂参加学习聚会。',
              'Goal: bring a Smoothie and a Lemon to the Auditorium (大礼堂).'),
            T('玩法：点击按钮，或者在下面输入命令（支持英文别名，例如 `go to GBC`）。',
              'How to play: click the buttons, or type commands below (English aliases such as '
              '`go to GBC` work too).'),
        ]
        if not self.has_player():
            line = None
            for path, number, text in self.remaining_stubs():
                if os.path.basename(path) == 'data.py':
                    line = number
            where = 'data.py:{}'.format(line) if line else 'data.py'
            lines.append(T('第一件事：在 {} 的最后创建 Player 对象，例如 me = Player("你的名字", sather_gate)。'.format(where),
                           'First step: create the player at the bottom of {} (see Q1), e.g. '
                           'me = Player("your name", sather_gate).'.format(where)))
            return lines

        stubs = self.remaining_stubs()
        if stubs:
            lines.append(T('还没删掉的 *YOUR CODE HERE* 标记：',
                           'Leftover *YOUR CODE HERE* markers:'))
            for path, number, _text in stubs:
                lines.append('    {}:{}'.format(os.path.basename(path), number))
        else:
            lines.append(T('不错：*YOUR CODE HERE* 标记都已经删掉了。',
                           'Nice: all *YOUR CODE HERE* markers are gone.'))

        for method_name, zh, en in METHOD_HINTS:
            lines.append('    [{}] {}'.format(self.location_of(method_name), T(zh, en)))
        lines.append(T('更多说明见 README.md / Questions.md（中英双语）。',
                       'More details are in README.md / Questions.md (bilingual).'))
        return lines


# =============================================================================
# AdventureGUI：tkinter 界面 / the tkinter interface
# =============================================================================

class AdventureGUI(object):
    def __init__(self, root):
        self.root = root
        self.session = GameSession()
        self.win_shown = False
        self.missing_player_warned = False
        self.font_family = _pick_font_family(root)
        self._configure_style()
        self._build_widgets()
        self._welcome()
        self.refresh()

    # ------------------------------------------------------------ 界面搭建
    def _configure_style(self):
        style = ttk.Style(self.root)
        family = self.font_family
        if not family:
            return
        for name, size in (('TLabel', 12), ('TButton', 12), ('TLabelframe.Label', 12),
                           ('TCheckbutton', 12), ('TCombobox', 12), ('TEntry', 12)):
            style.configure(name, font=(family, size))
        style.configure('Title.TLabel', font=(family, 17, 'bold'))
        style.configure('Place.TLabel', font=(family, 15, 'bold'))
        style.configure('Goal.TLabel', font=(family, 12), foreground='#555555')
        style.configure('Desc.TLabel', font=(family, 11), foreground='#666666')

    def _build_widgets(self):
        self.root.title(WINDOW_TITLE)
        self.root.columnconfigure(0, weight=1)
        # 主体部分按内容取自然高度（不会被压扁），多余的/不足的高度都给日志区
        # （日志自带滚动条，被压扁也不会丢信息）。
        # The body keeps its natural height; slack (and shortfall) goes to the log,
        # which has a scrollbar.
        self.root.rowconfigure(1, weight=0)
        self.root.rowconfigure(2, weight=1)
        self.root.report_callback_exception = self._report_callback_exception

        # ---- 顶部工具条 / top bar
        top = ttk.Frame(self.root, padding=(10, 8, 10, 4))
        top.grid(row=0, column=0, sticky='ew')
        ttk.Label(top, text=T('校园冒险', 'Adventure'), style='Title.TLabel').pack(side='left')
        ttk.Label(top, text=T('目标：把 Smoothie 和 Lemon 带去大礼堂',
                              'Goal: bring Smoothie + Lemon to 大礼堂'),
                  style='Goal.TLabel').pack(side='left', padx=12)
        ttk.Button(top, text=T('重新加载代码', 'Reload code'),
                   command=self.reload_code).pack(side='right')
        ttk.Button(top, text=T('重新开始', 'Restart'),
                   command=self.restart).pack(side='right', padx=6)
        self.lang_box = ttk.Combobox(top, width=11, state='readonly',
                                     values=[label for _code, label in LANGUAGE_CHOICES])
        self.lang_box.set(dict((code, label) for code, label in LANGUAGE_CHOICES)[LANG])
        self.lang_box.pack(side='right', padx=6)
        self.lang_box.bind('<<ComboboxSelected>>', self.change_language)
        ttk.Label(top, text=T('语言', 'Language')).pack(side='right')

        # ---- 中间主体 / main area
        body = ttk.Frame(self.root, padding=(10, 4, 10, 4))
        body.grid(row=1, column=0, sticky='nsew')
        body.columnconfigure(0, weight=3)
        body.columnconfigure(1, weight=2)
        body.rowconfigure(0, weight=1)

        left = ttk.Frame(body)
        left.grid(row=0, column=0, sticky='nsew', padx=(0, 8))
        left.columnconfigure(0, weight=1)
        left.rowconfigure(1, weight=1)
        right = ttk.Frame(body)
        right.grid(row=0, column=1, sticky='nsew')
        right.columnconfigure(0, weight=1)
        right.rowconfigure(2, weight=1)

        place_frame = ttk.Labelframe(left, text=T('当前位置', 'Current place'), padding=6)
        place_frame.grid(row=0, column=0, sticky='ew')
        place_frame.columnconfigure(0, weight=1)
        self.place_label = ttk.Label(place_frame, text='', style='Place.TLabel')
        self.place_label.grid(row=0, column=0, sticky='w')
        self.place_desc = ttk.Label(place_frame, text='', wraplength=580, justify='left',
                                    style='Desc.TLabel')
        self.place_desc.grid(row=1, column=0, sticky='w', pady=(2, 6))
        place_buttons = ttk.Frame(place_frame)
        place_buttons.grid(row=2, column=0, sticky='w')
        ttk.Button(place_buttons, text=T('查看', 'Look'),
                   command=self.do_look).pack(side='left')
        ttk.Button(place_buttons, text=T('检查背包', 'Check backpack'),
                   command=self.do_backpack).pack(side='left', padx=6)
        ttk.Button(place_buttons, text=T('提示', 'Hint'),
                   command=self.show_hints).pack(side='left')
        ttk.Button(place_buttons, text=T('命令列表', 'Help'),
                   command=self.show_help).pack(side='left', padx=6)

        self.exits_frame = ttk.Labelframe(left, text=T('出口（点一下就走过去）',
                                                       'Exits (click to walk there)'), padding=6)
        self.exits_frame.grid(row=1, column=0, sticky='nsew', pady=(6, 0))
        self.exits_frame.columnconfigure(0, weight=1)

        self.things_frame = ttk.Labelframe(right, text=T('这里的物品', 'Things here'), padding=6)
        self.things_frame.grid(row=0, column=0, sticky='ew')
        self.things_frame.columnconfigure(0, weight=1)
        self.characters_frame = ttk.Labelframe(right, text=T('这里的人', 'People here'), padding=6)
        self.characters_frame.grid(row=1, column=0, sticky='ew', pady=(6, 0))
        self.characters_frame.columnconfigure(0, weight=1)
        self.backpack_frame = ttk.Labelframe(right, text=T('背包', 'Backpack'), padding=6)
        self.backpack_frame.grid(row=2, column=0, sticky='nsew', pady=(6, 0))
        self.backpack_frame.columnconfigure(0, weight=1)

        # ---- 日志 / game log
        log_frame = ttk.Labelframe(self.root, text=T('游戏日志（你代码里 print 的内容都会出现在这里）',
                                                     'Game log (everything your code prints)'),
                                   padding=6)
        log_frame.grid(row=2, column=0, sticky='nsew', padx=10, pady=(4, 0))
        log_frame.rowconfigure(0, weight=1)
        log_frame.columnconfigure(0, weight=1)
        self.log_view = scrolledtext.ScrolledText(log_frame, wrap='word', height=7,
                                                  state='disabled', borderwidth=0)
        self.log_view.grid(row=0, column=0, sticky='nsew')
        if self.font_family:
            self.log_view.configure(font=(self.font_family, 12))
        for tag, color in (('error', '#b00020'), ('hint', '#0b6bb5'), ('win', '#137333'),
                           ('system', '#8a5a00'), ('input', '#5f6368')):
            self.log_view.tag_configure(tag, foreground=color)

        # ---- 命令输入框 / command box
        bar = ttk.Frame(self.root, padding=(10, 6, 10, 10))
        bar.grid(row=3, column=0, sticky='ew')
        ttk.Label(bar, text='adventure>').pack(side='left')
        self.entry = ttk.Entry(bar)
        self.entry.pack(side='left', fill='x', expand=True, padx=6)
        self.entry.bind('<Return>', self.run_command)
        ttk.Button(bar, text=T('运行', 'Run'), command=self.run_command).pack(side='left')
        ttk.Label(bar, text=T('也可以在这里敲命令，支持英文别名',
                              'you can also type commands here; aliases work'),
                  style='Desc.TLabel').pack(side='left', padx=8)

        # ---- 窗口大小 / window size（真正的大小在 _autosize 里按内容调整）
        self.root.geometry('1080x700')
        self.root.minsize(880, 560)

    # ------------------------------------------------------------ 日志
    def log(self, text, tag=None):
        if not text:
            return
        if not text.endswith('\n'):
            text += '\n'
        self.log_view.configure(state='normal')
        self.log_view.insert('end', text, tag)
        self.log_view.configure(state='disabled')
        self.log_view.see('end')

    def _snapshot_log(self):
        """把日志内容按 (标签, 文本) 存下来，切换语言时用来还原。"""
        entries = []
        current_tag = None
        for kind, value, _index in self.log_view.dump('1.0', 'end-1c', text=True, tag=True):
            if kind == 'text':
                entries.append((current_tag, value))
            elif kind == 'tagon':
                current_tag = value
            elif kind == 'tagoff':
                current_tag = None
        return entries

    def _report_callback_exception(self, exc_type, exc_value, exc_tb):
        self.log(''.join(traceback.format_exception(exc_type, exc_value, exc_tb)), 'error')

    # ------------------------------------------------------------ 开场白
    def _welcome(self):
        message = getattr(self.session.adventure, 'WELCOME_MESSAGE', None)
        if message:
            self.log(message, 'system')
        else:
            self.log(T(
                '欢迎来到冒险游戏！\n'
                '你是计算机系的学生，正在校园里寻找学习聚会要带的零食。\n'
                '目标：带上一杯奶昔（Smoothie）和一个柠檬（Lemon），去大礼堂。',
                'Welcome to the adventure game!\n'
                'You are a CS student looking for snacks before the study party.\n'
                'Goal: bring a Smoothie and a Lemon to the Auditorium (大礼堂).'), 'system')
        if not self.session.has_player():
            self._warn_missing_player()

    def _warn_missing_player(self):
        if self.missing_player_warned:
            return
        self.missing_player_warned = True
        line = None
        for path, number, _text in self.session.remaining_stubs():
            if os.path.basename(path) == 'data.py':
                line = number
        where = 'data.py:{}'.format(line) if line else 'data.py'
        self.log(T(
            '糟糕！还没有玩家：请先完成 Q1，在 {} 的最后创建 Player 对象，'
            '例如：me = Player("你的名字", sather_gate)\n'
            '（改完以后点右上角的“重新加载代码”。）'.format(where),
            'No player yet: do Q1 first - create the player at the bottom of {}, e.g. '
            'me = Player("your name", sather_gate)\n'
            '(Then click "Reload code" in the top-right corner.)'.format(where)), 'hint')

    def _show_load_error(self):
        self.log(T('载入 data.py / classes.py 失败，下面是 Python 的错误信息：',
                   'Could not import data.py / classes.py. Python says:'), 'error')
        self.log(self.session.load_error, 'error')
        self.log(T('改完代码后点右上角的“重新加载代码”再试一次。',
                   'Fix the code, then click "Reload code" and try again.'), 'hint')

    # ------------------------------------------------------------ 刷新界面
    def refresh(self):
        for frame in (self.exits_frame, self.things_frame,
                      self.characters_frame, self.backpack_frame):
            for child in frame.winfo_children():
                child.destroy()

        if self.session.load_error:
            self.place_label.configure(text=T('载入失败', 'Loading failed'))
            self.place_desc.configure(text=T('请先修好 data.py / classes.py 里的错误。',
                                             'Fix the errors in data.py / classes.py first.'))
            note = T('载入失败，先看看下面的错误信息。',
                     'Loading failed - see the error below.')
            self._render_note(self.exits_frame, note)
            self._render_note(self.things_frame, note)
            self._render_note(self.characters_frame, note)
            self._render_note(self.backpack_frame, note)
            self._show_load_error()
            return

        if not self.session.has_player():
            self.place_label.configure(text=T('还没有玩家', 'No player yet'))
            self.place_desc.configure(text=T(
                '在 data.py 的最后创建 Player 对象（Q1），然后点“重新加载代码”。',
                'Create the Player object at the bottom of data.py (Q1), then click "Reload code".'))
            self._render_note(self.exits_frame, T('完成 Q1 之后，这里会显示可以去的地方。',
                                                  'Finish Q1 and the places you can walk to show '
                                                  'up here.'))
            self._render_note(self.things_frame, '—')
            self._render_note(self.characters_frame, '—')
            self._render_note(self.backpack_frame, T('背包还是空的。', 'Your backpack is empty.'))
            self._warn_missing_player()
            return

        view = self.session.view()
        if view is None:
            self.place_label.configure(text=T('拿不到玩家位置', 'No player place'))
            self.place_desc.configure(text=T(
                'me.place 好像被改坏了：检查 data.py 中创建玩家时传入的地点。',
                'me.place looks broken: check the place you passed to Player(...) in data.py.'))
            return

        lock_mark = ' 🔒' if view['locked'] else ''
        self.place_label.configure(text=view['name'] + lock_mark)
        self.place_desc.configure(text=view['description'])
        self._render_exits(view['exits'])
        self._render_things(view['things'])
        self._render_characters(view['characters'])
        self._render_backpack(view['backpack'])
        self._autosize()

    def _autosize(self):
        """把窗口调整到刚好放得下内容（不超过屏幕，且只增不减）。

        Resize the window to fit its content, capped by the screen size; the window
        only ever grows, so the panels are never squeezed.  The log keeps its
        scrollbar, so it can absorb a shortfall on small screens.
        """
        self.root.update_idletasks()
        need_width = min(max(self.root.winfo_reqwidth(), 880), 1120)
        need_height = min(self.root.winfo_reqheight(),
                          max(self.root.winfo_screenheight() - 110, 560))
        need_height = max(need_height, 560)
        current_width = max(self.root.winfo_width(), 1)
        current_height = max(self.root.winfo_height(), 1)
        if need_width > current_width or need_height > current_height:
            self.root.geometry('{}x{}'.format(max(need_width, current_width),
                                              max(need_height, current_height)))

    def _render_exits(self, exits):
        if not exits:
            ttk.Label(self.exits_frame, text=T('这里没有出口。', 'No exits from here.')).pack(anchor='w')
            return
        for exit_info in exits:
            row = ttk.Frame(self.exits_frame)
            row.pack(fill='x', pady=2)
            label = exit_info['name']
            if exit_info['locked']:
                label += '  🔒 ' + T('已上锁', 'locked')
            ttk.Button(row, text=T('前往 ', 'Go to ') + label, width=20,
                       command=lambda name=exit_info['name']: self.do_go(name)).pack(side='left')
            if exit_info['locked']:
                ttk.Button(row, text=T('解锁', 'Unlock'),
                           command=lambda name=exit_info['name']: self.do_unlock(name)).pack(side='left', padx=4)
            if exit_info['description']:
                ttk.Label(row, text=exit_info['description'], style='Desc.TLabel',
                          wraplength=260, justify='left').pack(side='left', padx=6)

    def _render_things(self, things):
        if not things:
            ttk.Label(self.things_frame, text=T('这里什么也没有。', 'Nothing here.')).pack(anchor='w')
            return
        for thing in things:
            row = ttk.Frame(self.things_frame)
            row.pack(fill='x', pady=2)
            ttk.Button(row, text=T('拿走 ', 'Take ') + thing['name'],
                       command=lambda name=thing['name']: self.do_take(name)).pack(side='left')
            ttk.Label(row, text=thing['description'], style='Desc.TLabel',
                      wraplength=260, justify='left').pack(side='left', padx=6)

    def _render_characters(self, characters):
        if not characters:
            ttk.Label(self.characters_frame, text=T('这里没有别人。', 'Nobody here.')).pack(anchor='w')
            return
        for character in characters:
            row = ttk.Frame(self.characters_frame)
            row.pack(fill='x', pady=2)
            ttk.Button(row, text=T('交谈 ', 'Talk to ') + character['name'],
                       command=lambda name=character['name']: self.do_talk(name)).pack(side='left')

    def _render_backpack(self, items):
        if not items:
            ttk.Label(self.backpack_frame, text=T('背包是空的。', 'Your backpack is empty.')).pack(anchor='w')
            return
        for item in items:
            line = '• ' + item['name']
            if item['description']:
                line += ' - ' + item['description']
            ttk.Label(self.backpack_frame, text=line, wraplength=300,
                      justify='left').pack(anchor='w', pady=1)

    def _render_note(self, frame, text):
        """在动态面板里放一句占位说明 / placeholder line inside a dynamic panel."""
        ttk.Label(frame, text=text, style='Desc.TLabel', wraplength=380,
                  justify='left').pack(anchor='w')

    # ------------------------------------------------------------ 游戏操作
    def perform(self, command, method_name, *args):
        """执行一次操作：打印命令 -> 调用学生代码 -> 显示输出 -> 给出提示 -> 刷新。"""
        self.log('\nadventure> ' + command, 'input')
        before = self.session.signature()
        output, error = self.session.call(method_name, *args)
        if output:
            self.log(output)
        if error:
            self.log(error, 'error')
            self.log(self.session.error_hint(method_name), 'hint')
        elif method_name == 'talk_to' and not output.strip():
            # 对话一定会打印台词，这里什么都没打印，说明方法还没写完。
            self.log(self.session.no_change_hint('talk_to'), 'hint')
        elif method_name in ('go_to', 'take', 'unlock') and before == self.session.signature():
            self.log(self.session.no_change_hint(method_name), 'hint')
        self.refresh()
        self.check_win()

    def do_look(self):
        self.perform('look', 'look')

    def do_backpack(self):
        self.perform('check backpack', 'check_backpack')

    def do_go(self, name):
        self.perform('go to {}'.format(name), 'go_to', name)

    def do_take(self, name):
        self.perform('take {}'.format(name), 'take', name)

    def do_talk(self, name):
        self.perform('talk to {}'.format(name), 'talk_to', name)

    def do_unlock(self, name):
        self.perform('unlock {}'.format(name), 'unlock', name)

    def run_command(self, event=None):
        line = self.entry.get().strip()
        if not line:
            return 'break'
        self.entry.delete(0, 'end')
        try:
            operator, operand = self.session.parse(line)
        except SyntaxError as error:
            self.log('\nadventure> ' + line, 'input')
            self.log('ERROR: {}'.format(error), 'error')
            self.log(T('命令格式不对。点“命令列表 Help”看看正确写法，例如 `go to 大草坪`、'
                       '`talk to 杰瑞`、`take Lemon`。',
                       'That command is malformed. Click "Help" for the correct form, e.g. '
                       '`go to 大草坪`, `talk to 杰瑞`, `take Lemon`.'), 'hint')
            return 'break'
        except Exception:
            self.log('\nadventure> ' + line, 'input')
            self.log(traceback.format_exc(), 'error')
            return 'break'
        self._dispatch(operator, operand, line)
        return 'break'

    def _dispatch(self, operator, operand, line=''):
        if operator == 'help':
            self.show_help()
        elif operator == 'look':
            self.perform('look', 'look')
        elif operator == 'check_backpack':
            self.perform('check backpack', 'check_backpack')
        elif operator == 'go_to':
            self.perform('go to {}'.format(operand), 'go_to', operand)
        elif operator == 'take':
            self.perform('take {}'.format(operand), 'take', operand)
        elif operator == 'talk_to':
            self.perform('talk to {}'.format(operand), 'talk_to', operand)
        elif operator == 'unlock':
            self.perform('unlock {}'.format(operand), 'unlock', operand)
        else:
            self.log('\nadventure> ' + line, 'input')
            self.log(T('无效命令：{}。点“命令列表 Help”看看有哪些命令。'.format(operator),
                       'Invalid command: {}. Click "Help" to see the command list.'.format(operator)),
                     'error')

    def check_win(self):
        if self.win_shown or not self.session.is_win():
            return
        self.win_shown = True
        message = getattr(self.session.adventure, 'WIN_MESSAGE', None) or T(
            '你在大礼堂赶上了学习聚会，恭喜通关！',
            'You arrived at the Auditorium in time. Congratulations!')
        self.log(message, 'win')
        messagebox.showinfo(T('恭喜通关', 'You win'), message)

    # ------------------------------------------------------------ 其它按钮
    def show_help(self):
        self.log(T('\n可用命令 / available commands:', '\nAvailable commands:'), 'hint')
        for usage in self.session.command_formats():
            self.log('    ' + usage, 'hint')
        self.log(T('提示：命令里的地名既可以用中文，也可以用英文别名，例如 go to GBC。',
                   'Tip: place names accept both Chinese and English aliases, e.g. `go to GBC`.'), 'hint')

    def show_hints(self):
        self.log('\n' + T('— 提示 —', '— Hints —'), 'hint')
        for line in self.session.hint_lines():
            self.log(line, 'hint')

    def change_language(self, event=None):
        global LANG
        labels = dict((label, code) for code, label in LANGUAGE_CHOICES)
        LANG = labels.get(self.lang_box.get(), LANG)
        self._rebuild_ui()

    def _rebuild_ui(self):
        """切换语言后重建一次界面（保留日志内容）。"""
        entries = self._snapshot_log()
        for child in self.root.winfo_children():
            child.destroy()
        self._build_widgets()
        for tag, text in entries:
            self.log(text, tag)
        self.refresh()

    def reload_code(self):
        if self.session.load(do_reload=True):
            self.log('\n' + T('— 已重新加载 classes.py / data.py —',
                              '— reloaded classes.py / data.py —'), 'system')
        self.win_shown = False
        self.missing_player_warned = False
        self.refresh()
        if self.session.load_error:
            self._show_load_error()

    def restart(self):
        self.reload_code()
        self.log(T('— 重新开始 —', '— restarting —'), 'system')
        self._welcome()


def _pick_font_family(root):
    """挑一个系统中存在的中文字体，挑不到就返回 None（用 Tk 默认字体）。"""
    try:
        available = set(tkfont.families(root))
    except Exception:
        return None
    for name in ('PingFang SC', 'Hiragino Sans GB', 'Heiti SC',
                 'Microsoft YaHei UI', 'Microsoft YaHei', 'SimHei',
                 'Noto Sans CJK SC', 'Source Han Sans SC', 'WenQuanYi Micro Hei'):
        if name in available:
            return name
    return None


def main():
    root = tk.Tk()
    AdventureGUI(root)
    root.mainloop()


if __name__ == '__main__':
    main()
